<?php

/**
 * @file
 * Install, update and uninstall functions for the Product set module.
 */

use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_install().
 */
function commerce_product_set_install() {
  // Allow all roles to view published products.
  user_role_grant_permissions(AccountInterface::ANONYMOUS_ROLE, ['view commerce_product_set']);
  user_role_grant_permissions(AccountInterface::AUTHENTICATED_ROLE, ['view commerce_product_set']);
}
